M48
; DRILL file {KiCad 9.0.7} date 2026-03-01T08:55:15+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-01T08:55:15+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C5.000
%
G90
G05
T1
X47.387Y-42.475
X57.387Y-42.475
T2
X47.387Y-51.375
X52.387Y-53.575
X57.387Y-51.375
T3
X52.387Y-47.625
M30
